"""
AutoCurriculum — PAIRED-inspired self-play difficulty scheduler.

Algorithm:
  - Track a sliding window of recent episode rewards.
  - Compute success_rate = fraction of episodes with reward > success_threshold.
  - Target difficulty is adjusted to keep success_rate near target_rate (default 0.5).
  - difficulty ∈ [0.0, 1.0] is exposed in the observation and used to parameterize
    scenario generation at reset() time.

Curriculum dimensions controlled:
  1. buyer_aggressiveness: 0=cooperative, 1=maximally exploitative
  2. payment_delay_multiplier: scales the SimPy payment delay distribution
  3. compliance_risk_multiplier: multiplies Section 43B(h) breach probability
  4. invoice_volume_multiplier: scales invoice generation rate
  5. working_capital_stress: scales initial cash balance (lower = harder)

PAIRED inspiration:
  The difficulty target tracks the agent's learning frontier — the hardest
  scenario where success is still ~50%. This maximises gradient signal and
  prevents the agent from overfitting to either trivially easy or impossibly
  hard scenarios.

Self-play aspect (Theme 4):
  When self_play_enabled=True, a second "adversarial buyer" parameterization
  is generated by maximising the agent's expected regret — analogous to
  OpenAI's hide-and-seek where opponents drive emergent tool use.
"""

from __future__ import annotations

import math
from collections import deque
from dataclasses import dataclass, field
from random import Random
from typing import Any, Dict, List, Optional


@dataclass
class CurriculumParams:
    """Scenario parameterization produced by the AutoCurriculum."""

    difficulty: float                     # 0.0 (easy) → 1.0 (hard)
    buyer_aggressiveness: float           # 0.0 → 1.0
    payment_delay_multiplier: float       # 1.0 = baseline delay
    compliance_risk_multiplier: float     # 1.0 = baseline breach rate
    invoice_volume_multiplier: float      # 1.0 = baseline volume
    working_capital_stress: float         # 1.0 = full cash; 0.1 = near-empty
    scenario_complexity: int              # 1-5 simultaneous stress factors


@dataclass
class CurriculumState:
    """Internal state of the AutoCurriculum."""

    recent_rewards: deque = field(default_factory=lambda: deque(maxlen=50))
    difficulty: float = 0.5
    success_rate: float = 0.5
    episode_count: int = 0
    adjustment_step_size: float = 0.05
    target_success_rate: float = 0.5


class AutoCurriculum:
    """
    PAIRED-inspired curriculum that tracks agent performance and adjusts
    scenario difficulty to maintain the learning frontier.

    Usage:
      curriculum = AutoCurriculum(target_success_rate=0.50)
      params = curriculum.sample_params(rng)         # at episode start
      ...
      curriculum.record_episode(terminal_reward)     # at episode end
    """

    def __init__(
        self,
        target_success_rate: float = 0.50,
        success_threshold: float = 0.55,   # min reward to count as success
        window_size: int = 20,
        step_size: float = 0.05,
        rng_seed: Optional[int] = None,
    ) -> None:
        self._target = target_success_rate
        self._threshold = success_threshold
        self._step = step_size
        self._state = CurriculumState(
            recent_rewards=deque(maxlen=window_size),
            target_success_rate=target_success_rate,
        )
        self._rng = Random(rng_seed)

    # ── Episode lifecycle ──────────────────────────────────────────────────────

    def record_episode(self, terminal_reward: float) -> None:
        """Call at end of each episode with the terminal reward."""
        self._state.recent_rewards.append(terminal_reward)
        self._state.episode_count += 1
        self._update_difficulty()

    def _update_difficulty(self) -> None:
        rewards = list(self._state.recent_rewards)
        if len(rewards) < 5:
            return  # not enough data yet

        success_rate = sum(1 for r in rewards if r > self._threshold) / len(rewards)
        self._state.success_rate = success_rate

        # PAIRED learning frontier: push difficulty toward 50% success zone
        gap = success_rate - self._target
        delta = self._step * math.tanh(gap * 4.0)  # tanh for smooth adjustment
        new_d = self._state.difficulty + delta
        self._state.difficulty = max(0.05, min(0.95, new_d))

    # ── Parameter sampling ─────────────────────────────────────────────────────

    def sample_params(self, rng: Optional[Random] = None) -> CurriculumParams:
        """
        Generate scenario parameters for the current difficulty level.

        Interpolates between easy (d=0) and hard (d=1) parameter sets:
          - d=0: cooperative buyers, standard delays, no compliance risk
          - d=1: hostile buyers, 50% delayed payments, full 43B(h) risk
        """
        rng = rng or self._rng
        d = self._state.difficulty

        # Linear interpolation with jitter for diversity
        jitter = rng.uniform(-0.05, 0.05)
        d_j = max(0.0, min(1.0, d + jitter))

        buyer_aggressiveness = _lerp(0.10, 0.90, d_j)
        payment_delay_mult = _lerp(0.80, 1.50, d_j)  # 80%→150% of baseline delay
        compliance_risk_mult = _lerp(0.0, 2.0, d_j)
        invoice_volume_mult = _lerp(0.70, 1.40, d_j)
        working_capital_stress = _lerp(1.0, 0.20, d_j)  # harder = less cash

        # Scenario complexity: number of simultaneous stress factors
        complexity = max(1, int(d_j * 5) + rng.choice([0, 0, 1]))

        return CurriculumParams(
            difficulty=round(d_j, 3),
            buyer_aggressiveness=round(buyer_aggressiveness, 3),
            payment_delay_multiplier=round(payment_delay_mult, 3),
            compliance_risk_multiplier=round(compliance_risk_mult, 3),
            invoice_volume_multiplier=round(invoice_volume_mult, 3),
            working_capital_stress=round(working_capital_stress, 3),
            scenario_complexity=complexity,
        )

    # ── Self-play adversarial parameterization ─────────────────────────────────

    def sample_adversarial_params(
        self,
        agent_recent_rewards: List[float],
        rng: Optional[Random] = None,
    ) -> CurriculumParams:
        """
        Self-play extension: generate a scenario that maximises agent regret.

        Strategy:
          1. Compute agent's recent average reward.
          2. Set difficulty slightly above the agent's comfort zone.
          3. Introduce one unexpected stress factor (compliance shock,
             buyer default event, vendor crisis).

        This is analogous to OpenAI hide-and-seek where the opponent's
        strategy forces the agent to discover new tools.
        """
        rng = rng or self._rng
        if not agent_recent_rewards:
            return self.sample_params(rng)

        avg_r = sum(agent_recent_rewards) / len(agent_recent_rewards)
        # Push difficulty just beyond where agent currently succeeds
        adversarial_d = min(0.95, avg_r + 0.15)

        params = CurriculumParams(
            difficulty=round(adversarial_d, 3),
            buyer_aggressiveness=round(_lerp(0.5, 1.0, adversarial_d), 3),
            payment_delay_multiplier=round(_lerp(1.0, 1.6, adversarial_d), 3),
            compliance_risk_multiplier=round(_lerp(0.5, 3.0, adversarial_d), 3),
            invoice_volume_multiplier=round(_lerp(0.9, 1.5, adversarial_d), 3),
            working_capital_stress=round(_lerp(0.8, 0.1, adversarial_d), 3),
            scenario_complexity=rng.randint(2, 5),
        )
        return params

    # ── Constitutional AI self-improvement ─────────────────────────────────────

    def check_constitutional_violation(
        self,
        action_app: Optional[str],
        action_endpoint: Optional[str],
        kpis: Dict[str, Any],
        constitutional_rules: tuple,
    ) -> bool:
        """
        Check if the current action violates any constitutional rule.

        Returns True if a violation is detected.
        This signal is used to cap the reward at 0.05 (Constitutional AI pattern).

        Rules checked symbolically:
          Rule 0: Never violate solvency — taking no action when cash_buffer < 1d
          Rule 1: Always check compliance before Samadhaan
          Rule 2: Prefer TReDS when it's available and cheaper
          Rule 3: Keep HHI < 0.25 (don't concentrate further)
        """
        solvency_ok = kpis.get("solvency_ok", True)
        cash_buffer = float(kpis.get("cash_buffer_days", 999))
        compliance_breaches = int(kpis.get("compliance_breach_count", 0))
        hhi = float(kpis.get("concentration_risk_hhi", 0))
        treds_eligible = float(kpis.get("treds_eligible_amount", 0))

        # Rule 0: near-insolvency but agent is not drawing financing
        if cash_buffer < 1.0 and action_app not in ("bank_app", "treds_app", None):
            return True

        # Rule 1: Samadhaan filed without compliance check
        if (action_app == "compliance_app"
                and action_endpoint == "prepare_samadhaan_case"
                and compliance_breaches == 0):
            return True  # Samadhaan when no breach is a misuse

        # Rule 3: Don't worsen concentration when HHI already critical
        # (no specific action triggers this — tracked elsewhere)

        return False

    # ── State accessors ────────────────────────────────────────────────────────

    @property
    def difficulty(self) -> float:
        return self._state.difficulty

    @property
    def success_rate(self) -> float:
        return self._state.success_rate

    @property
    def episode_count(self) -> int:
        return self._state.episode_count

    def state_dict(self) -> Dict[str, Any]:
        return {
            "difficulty": self._state.difficulty,
            "success_rate": self._state.success_rate,
            "episode_count": self._state.episode_count,
            "recent_rewards_mean": (
                sum(self._state.recent_rewards) / max(len(self._state.recent_rewards), 1)
            ),
        }


def _lerp(a: float, b: float, t: float) -> float:
    return a + (b - a) * t
